/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package xueqiao.company.service.maintenance.webapi.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class NewUpgradeSchedule implements org.apache.thrift.TBase<NewUpgradeSchedule, NewUpgradeSchedule._Fields>, java.io.Serializable, Cloneable, Comparable<NewUpgradeSchedule> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("NewUpgradeSchedule");

  private static final org.apache.thrift.protocol.TField COMPANY_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("companyIds", org.apache.thrift.protocol.TType.SET, (short)1);
  private static final org.apache.thrift.protocol.TField TARGET_VERSION_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("targetVersionId", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField OPERATOR_FIELD_DESC = new org.apache.thrift.protocol.TField("operator", org.apache.thrift.protocol.TType.STRING, (short)4);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new NewUpgradeScheduleStandardSchemeFactory());
    schemes.put(TupleScheme.class, new NewUpgradeScheduleTupleSchemeFactory());
  }

  public Set<Long> companyIds; // optional
  public long targetVersionId; // optional
  public String operator; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    COMPANY_IDS((short)1, "companyIds"),
    TARGET_VERSION_ID((short)2, "targetVersionId"),
    OPERATOR((short)4, "operator");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // COMPANY_IDS
          return COMPANY_IDS;
        case 2: // TARGET_VERSION_ID
          return TARGET_VERSION_ID;
        case 4: // OPERATOR
          return OPERATOR;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __TARGETVERSIONID_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  private _Fields optionals[] = {_Fields.COMPANY_IDS,_Fields.TARGET_VERSION_ID,_Fields.OPERATOR};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.COMPANY_IDS, new org.apache.thrift.meta_data.FieldMetaData("companyIds", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.SetMetaData(org.apache.thrift.protocol.TType.SET, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64))));
    tmpMap.put(_Fields.TARGET_VERSION_ID, new org.apache.thrift.meta_data.FieldMetaData("targetVersionId", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.OPERATOR, new org.apache.thrift.meta_data.FieldMetaData("operator", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(NewUpgradeSchedule.class, metaDataMap);
  }

  public NewUpgradeSchedule() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public NewUpgradeSchedule(NewUpgradeSchedule other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetCompanyIds()) {
      Set<Long> __this__companyIds = new HashSet<Long>(other.companyIds);
      this.companyIds = __this__companyIds;
    }
    this.targetVersionId = other.targetVersionId;
    if (other.isSetOperator()) {
      this.operator = other.operator;
    }
  }

  public NewUpgradeSchedule deepCopy() {
    return new NewUpgradeSchedule(this);
  }

  @Override
  public void clear() {
    this.companyIds = null;
    setTargetVersionIdIsSet(false);
    this.targetVersionId = 0;
    this.operator = null;
  }

  public int getCompanyIdsSize() {
    return (this.companyIds == null) ? 0 : this.companyIds.size();
  }

  public java.util.Iterator<Long> getCompanyIdsIterator() {
    return (this.companyIds == null) ? null : this.companyIds.iterator();
  }

  public void addToCompanyIds(long elem) {
    if (this.companyIds == null) {
      this.companyIds = new HashSet<Long>();
    }
    this.companyIds.add(elem);
  }

  public Set<Long> getCompanyIds() {
    return this.companyIds;
  }

  public NewUpgradeSchedule setCompanyIds(Set<Long> companyIds) {
    this.companyIds = companyIds;
    return this;
  }

  public void unsetCompanyIds() {
    this.companyIds = null;
  }

  /** Returns true if field companyIds is set (has been assigned a value) and false otherwise */
  public boolean isSetCompanyIds() {
    return this.companyIds != null;
  }

  public void setCompanyIdsIsSet(boolean value) {
    if (!value) {
      this.companyIds = null;
    }
  }

  public long getTargetVersionId() {
    return this.targetVersionId;
  }

  public NewUpgradeSchedule setTargetVersionId(long targetVersionId) {
    this.targetVersionId = targetVersionId;
    setTargetVersionIdIsSet(true);
    return this;
  }

  public void unsetTargetVersionId() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __TARGETVERSIONID_ISSET_ID);
  }

  /** Returns true if field targetVersionId is set (has been assigned a value) and false otherwise */
  public boolean isSetTargetVersionId() {
    return EncodingUtils.testBit(__isset_bitfield, __TARGETVERSIONID_ISSET_ID);
  }

  public void setTargetVersionIdIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __TARGETVERSIONID_ISSET_ID, value);
  }

  public String getOperator() {
    return this.operator;
  }

  public NewUpgradeSchedule setOperator(String operator) {
    this.operator = operator;
    return this;
  }

  public void unsetOperator() {
    this.operator = null;
  }

  /** Returns true if field operator is set (has been assigned a value) and false otherwise */
  public boolean isSetOperator() {
    return this.operator != null;
  }

  public void setOperatorIsSet(boolean value) {
    if (!value) {
      this.operator = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case COMPANY_IDS:
      if (value == null) {
        unsetCompanyIds();
      } else {
        setCompanyIds((Set<Long>)value);
      }
      break;

    case TARGET_VERSION_ID:
      if (value == null) {
        unsetTargetVersionId();
      } else {
        setTargetVersionId((Long)value);
      }
      break;

    case OPERATOR:
      if (value == null) {
        unsetOperator();
      } else {
        setOperator((String)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case COMPANY_IDS:
      return getCompanyIds();

    case TARGET_VERSION_ID:
      return Long.valueOf(getTargetVersionId());

    case OPERATOR:
      return getOperator();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case COMPANY_IDS:
      return isSetCompanyIds();
    case TARGET_VERSION_ID:
      return isSetTargetVersionId();
    case OPERATOR:
      return isSetOperator();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof NewUpgradeSchedule)
      return this.equals((NewUpgradeSchedule)that);
    return false;
  }

  public boolean equals(NewUpgradeSchedule that) {
    if (that == null)
      return false;

    boolean this_present_companyIds = true && this.isSetCompanyIds();
    boolean that_present_companyIds = true && that.isSetCompanyIds();
    if (this_present_companyIds || that_present_companyIds) {
      if (!(this_present_companyIds && that_present_companyIds))
        return false;
      if (!this.companyIds.equals(that.companyIds))
        return false;
    }

    boolean this_present_targetVersionId = true && this.isSetTargetVersionId();
    boolean that_present_targetVersionId = true && that.isSetTargetVersionId();
    if (this_present_targetVersionId || that_present_targetVersionId) {
      if (!(this_present_targetVersionId && that_present_targetVersionId))
        return false;
      if (this.targetVersionId != that.targetVersionId)
        return false;
    }

    boolean this_present_operator = true && this.isSetOperator();
    boolean that_present_operator = true && that.isSetOperator();
    if (this_present_operator || that_present_operator) {
      if (!(this_present_operator && that_present_operator))
        return false;
      if (!this.operator.equals(that.operator))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(NewUpgradeSchedule other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetCompanyIds()).compareTo(other.isSetCompanyIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCompanyIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.companyIds, other.companyIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetTargetVersionId()).compareTo(other.isSetTargetVersionId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTargetVersionId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.targetVersionId, other.targetVersionId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetOperator()).compareTo(other.isSetOperator());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOperator()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.operator, other.operator);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("NewUpgradeSchedule(");
    boolean first = true;

    if (isSetCompanyIds()) {
      sb.append("companyIds:");
      if (this.companyIds == null) {
        sb.append("null");
      } else {
        sb.append(this.companyIds);
      }
      first = false;
    }
    if (isSetTargetVersionId()) {
      if (!first) sb.append(", ");
      sb.append("targetVersionId:");
      sb.append(this.targetVersionId);
      first = false;
    }
    if (isSetOperator()) {
      if (!first) sb.append(", ");
      sb.append("operator:");
      if (this.operator == null) {
        sb.append("null");
      } else {
        sb.append(this.operator);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class NewUpgradeScheduleStandardSchemeFactory implements SchemeFactory {
    public NewUpgradeScheduleStandardScheme getScheme() {
      return new NewUpgradeScheduleStandardScheme();
    }
  }

  private static class NewUpgradeScheduleStandardScheme extends StandardScheme<NewUpgradeSchedule> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, NewUpgradeSchedule struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // COMPANY_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.SET) {
              {
                org.apache.thrift.protocol.TSet _set32 = iprot.readSetBegin();
                struct.companyIds = new HashSet<Long>(2*_set32.size);
                for (int _i33 = 0; _i33 < _set32.size; ++_i33)
                {
                  long _elem34;
                  _elem34 = iprot.readI64();
                  struct.companyIds.add(_elem34);
                }
                iprot.readSetEnd();
              }
              struct.setCompanyIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // TARGET_VERSION_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.targetVersionId = iprot.readI64();
              struct.setTargetVersionIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OPERATOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.operator = iprot.readString();
              struct.setOperatorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, NewUpgradeSchedule struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.companyIds != null) {
        if (struct.isSetCompanyIds()) {
          oprot.writeFieldBegin(COMPANY_IDS_FIELD_DESC);
          {
            oprot.writeSetBegin(new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I64, struct.companyIds.size()));
            for (long _iter35 : struct.companyIds)
            {
              oprot.writeI64(_iter35);
            }
            oprot.writeSetEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetTargetVersionId()) {
        oprot.writeFieldBegin(TARGET_VERSION_ID_FIELD_DESC);
        oprot.writeI64(struct.targetVersionId);
        oprot.writeFieldEnd();
      }
      if (struct.operator != null) {
        if (struct.isSetOperator()) {
          oprot.writeFieldBegin(OPERATOR_FIELD_DESC);
          oprot.writeString(struct.operator);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class NewUpgradeScheduleTupleSchemeFactory implements SchemeFactory {
    public NewUpgradeScheduleTupleScheme getScheme() {
      return new NewUpgradeScheduleTupleScheme();
    }
  }

  private static class NewUpgradeScheduleTupleScheme extends TupleScheme<NewUpgradeSchedule> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, NewUpgradeSchedule struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetCompanyIds()) {
        optionals.set(0);
      }
      if (struct.isSetTargetVersionId()) {
        optionals.set(1);
      }
      if (struct.isSetOperator()) {
        optionals.set(2);
      }
      oprot.writeBitSet(optionals, 3);
      if (struct.isSetCompanyIds()) {
        {
          oprot.writeI32(struct.companyIds.size());
          for (long _iter36 : struct.companyIds)
          {
            oprot.writeI64(_iter36);
          }
        }
      }
      if (struct.isSetTargetVersionId()) {
        oprot.writeI64(struct.targetVersionId);
      }
      if (struct.isSetOperator()) {
        oprot.writeString(struct.operator);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, NewUpgradeSchedule struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(3);
      if (incoming.get(0)) {
        {
          org.apache.thrift.protocol.TSet _set37 = new org.apache.thrift.protocol.TSet(org.apache.thrift.protocol.TType.I64, iprot.readI32());
          struct.companyIds = new HashSet<Long>(2*_set37.size);
          for (int _i38 = 0; _i38 < _set37.size; ++_i38)
          {
            long _elem39;
            _elem39 = iprot.readI64();
            struct.companyIds.add(_elem39);
          }
        }
        struct.setCompanyIdsIsSet(true);
      }
      if (incoming.get(1)) {
        struct.targetVersionId = iprot.readI64();
        struct.setTargetVersionIdIsSet(true);
      }
      if (incoming.get(2)) {
        struct.operator = iprot.readString();
        struct.setOperatorIsSet(true);
      }
    }
  }

}

